In [75]:
import numpy as np

In [76]:
import pandas as pd

In [77]:
df= pd.read_csv('en.csv')

In [78]:
df.head(5)

age  gender  rewe edu  pur
0   89  female  good  ug  yes
1   24  female  aerg  pg  yes
2   34  female  poor  pg   no
3   18  female  poor  pg  yes
4   16  female  aerg  ug   no

In [79]:
dft= df.iloc[:,2:]

In [80]:
dft

rewe    edu  pur
0   good     ug  yes
1   aerg     pg  yes
2   poor     pg   no
3   poor     pg  yes
4   aerg     ug   no
5   good  shool  yes
6   aerg  shool   no
7   aerg     ug  yes
8   poor  shool  yes
9   good     pg   no
10  aerg  shool  yes
11  aerg     ug   no
12  poor     ug  yes
13  poor  shool  yes

In [81]:
from sklearn .model_selection import train_test_split

In [100]:
a_train,a_test,y_train,y_test = train_test_split(dft.iloc[:,0:2],dft.iloc[:,-1],test_size=0.2)

In [83]:
a_train

rewe    edu
9   good     pg
13  poor  shool
11  aerg     ug
7   aerg     ug
2   poor     pg
1   aerg     pg
8   poor  shool
10  aerg  shool
5   good  shool
12  poor     ug
4   aerg     ug

In [84]:
a_test

rewe    edu
6  aerg  shool
3  poor     pg
0  good     ug

In [101]:
y_test

9      no
12    yes
13    yes
Name: pur, dtype: object

In [87]:
from sklearn .preprocessing import OrdinalEncoder

In [88]:
oe = OrdinalEncoder(categories=[['poor','aerg','good'],['shool','ug','pg']]) 

In [89]:
oe.fit(a_train)

OrdinalEncoder(categories=[['poor', 'aerg', 'good'], ['shool', 'ug', 'pg']])

In [90]:
a_train = oe.transform(a_train)
a_test = oe.transform(a_test)

In [91]:
a_train

array([[2., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.]])

In [92]:
a_test

array([[1., 0.],
       [0., 2.],
       [2., 1.]])

# labelen

In [106]:
from sklearn.preprocessing import LabelEncoder

In [111]:
le = LabelEncoder()

In [109]:
y_train

4      no
11     no
1     yes
5     yes
2      no
0     yes
3     yes
6      no
10    yes
7     yes
8     yes
Name: pur, dtype: object

In [112]:
le .fit(y_train)

LabelEncoder()

In [113]:
le.classes_

array(['no', 'yes'], dtype=object)

In [114]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [115]:
y_train

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [116]:
y_test

array([0, 1, 1])